apiVersion: v1
kind: Pod
metadata:
  name: redis-replication
  labels:
    app: redis-replication
spec:
  containers:
    - name: redis-replication-master-1
      image: docker.io/library/redis:7.2
      command: ["redis-server"]
      args: ["--appendonly", "yes", "--port", "6380"]
      ports:
        - containerPort: 6380
          hostPort: 6380
      volumeMounts:
        - name: master-data
          mountPath: /data

    - name: redis-replication-replica-1
      image: docker.io/library/redis:7.2
      command: ["redis-server"]
      args: ["--port", "6381", "--replicaof", "127.0.0.1", "6380"]
      ports:
        - containerPort: 6381
          hostPort: 6381
      volumeMounts:
        - name: replica1-data
          mountPath: /data

    - name: redis-replication-replica-2
      image: docker.io/library/redis:7.2
      command: ["redis-server"]
      args: ["--port", "6382", "--replicaof", "127.0.0.1", "6380"]
      ports:
        - containerPort: 6382
          hostPort: 6382
      volumeMounts:
        - name: replica2-data
          mountPath: /data

  volumes:
    - name: master-data
      hostPath:
        path: ./volumes/redis-replication/master
        type: DirectoryOrCreate
    - name: replica1-data
      hostPath:
        path: ./volumes/redis-replication/replica1
        type: DirectoryOrCreate
    - name: replica2-data
      hostPath:
        path: ./volumes/redis-replication/replica2
        type: DirectoryOrCreate
