---
- name: Deploy YugabyteDB on K8s via Helm
  hosts: k3s_server
  become: true
  vars:
    yb_operator_version: "2024.2.3"   # yugabytedb/yugabyte chart version
    k3s_proxy: "http://sproxy.104-dev.com.tw:3128"
    k3s_no_proxy: "172.24.40.32,172.24.40.33,172.24.40.34,10.42.0.0/16,10.43.0.0/16,127.0.0.1,localhost,.svc,.cluster.local,kubernetes"
  roles:
    - yugabyte_k8s_deploy
