# Bootstrap node — starts first, others join via this IP
[yb_bootstrap]
172.24.40.32 ansible_hostname=l-test-poc-1 yb_zone=idc yb_actual_ip=172.24.40.32

# Join nodes
[yb_join]
172.24.40.33 ansible_hostname=l-test-poc-2 yb_zone=idc yb_actual_ip=172.24.40.33
172.24.40.34 ansible_hostname=l-test-poc-3 yb_zone=idc yb_actual_ip=172.24.40.34
g-test-poc-1 yb_zone=gcp yb_actual_ip=10.160.152.11
g-test-poc-2 yb_zone=gcp yb_actual_ip=10.160.152.12

# All nodes
[yb_cluster:children]
yb_bootstrap
yb_join
