apiVersion: v1
kind: Service
metadata:
  name: private-demo
  namespace: private-demo
spec:
  type: ClusterIP
  selector:
    app: private-demo
  ports:
    - name: http
      port: 80
      targetPort: 80
