apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-app
  namespace: argocd
spec:
  project: dbaas
  source:
    repoURL: REPLACE_WITH_YOUR_GIT_REPO_URL
    targetRevision: HEAD
    path: clusters/lab/namespaces
  destination:
    server: https://kubernetes.default.svc
    namespace: dbaas-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
