apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hello-app.yaml
  - percona-operator.yaml
  - mysql-single.yaml
  - tidb-operator.yaml
  - tidb-cluster.yaml
  - tidb-monitor.yaml
  - redis-operator.yaml
  - redis-single.yaml
  - victoria-metrics.yaml
  - grafana.yaml
