apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: private-demo
  namespace: argocd
spec:
  project: dbaas
  source:
    repoURL: https://github.com/heavenruler/dba_career.git
    targetRevision: master
    path: dbaas/dbaas-gitops/clusters/lab/services/private-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: private-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
