apiVersion: v1
kind: Pod
metadata:
  name: redis-standalone
  labels:
    app: redis-standalone
spec:
  restartPolicy: Always
  containers:
    - name: redis-standalone-1
      image: docker.io/library/redis:7.2-alpine
      ports:
        - containerPort: 6379
          hostPort: 6379
      command:
        - redis-server
        - --appendonly
        - "yes"
