#!/usr/bin/env bash
# compare.sh — print VM vs K8s TPC-C comparison tables to stdout
# Usage: bash compare.sh <results_base> <topo> <scenario>
# Reads:  <results_base>/<topo>/<scenario>/{vm,k8s-unlimit,k8s-limit}/<latest>/summary.md
# Output: markdown tables (paste into compare.md manually)
set -euo pipefail

RESULT_BASE=${1:?Usage: $0 <results_base> <topo> <scenario>}
TOPO=${2:?topo required}
SCENARIO=${3:?scenario required}

BASE="${RESULT_BASE}/${TOPO}/${SCENARIO}"
THREAD_LEVELS=(16 32 64 128)
VARIANTS=(vm k8s-unlimit k8s-limit)

declare -A SUMMARY
for v in "${VARIANTS[@]}"; do
  d=$(ls -td "${BASE}/${v}"/*/ 2>/dev/null | head -1 || true)
  SUMMARY[$v]=""
  [[ -n "$d" && -f "${d}summary.md" ]] && SUMMARY[$v]="${d}summary.md"
done

# extract field from summary.md table: col=2(tpmC), 3(NO p99), 4(PAY p99)
_field() {
  local file=$1 t=$2 col=$3
  [[ -z "$file" || ! -f "$file" ]] && return
  awk -F'|' -v t="$t" -v c="$col" '
    /^\| *[0-9]+ *\|/ {
      gsub(/^[ \t]+|[ \t]+$/, "", $2)
      if ($2 == t) {
        f = $(c+1); gsub(/^[ \t]+|[ \t]+$/, "", f); gsub(",", "", f)
        print f
      }
    }' "$file"
}

_int_comma() {
  awk -v n="${1:-}" 'BEGIN {
    if (n == "") { printf "—"; exit }
    sgn = ""; if (n+0 < 0) { sgn = "-"; n = -n }
    s = sprintf("%d", int(n+0.5)); r = ""
    while (length(s) > 3) {
      r = "," substr(s, length(s)-2) r
      s = substr(s, 1, length(s)-3)
    }
    printf "%s%s%s", sgn, s, r
    exit
  }'
}

_num() { awk -v n="${1:-}" -v f="${2:-%.1f}" 'BEGIN { if (n=="") printf "—"; else printf f, n+0 }'; }
_pct() {
  awk -v a="${1:-}" -v b="${2:-}" 'BEGIN {
    if (a=="" || b=="" || b+0==0) printf "—"
    else printf "%+.1f%%", (a/b - 1) * 100
  }'
}
_delta() {
  awk -v a="${1:-}" -v b="${2:-}" 'BEGIN {
    if (a=="" || b=="") printf "—"; else printf "%+.1f", (a - b)
  }'
}

# find peak tpmC (value, threads) for a variant
_peak() {
  local v=$1 best_v="" best_t="" cur
  for t in "${THREAD_LEVELS[@]}"; do
    cur=$(_field "${SUMMARY[$v]}" "$t" 2)
    [[ -z "$cur" ]] && continue
    if [[ -z "$best_v" ]] || awk -v a="$cur" -v b="$best_v" 'BEGIN{exit !(a>b)}'; then
      best_v=$cur; best_t=$t
    fi
  done
  echo "${best_v}|${best_t}"
}

# --- output ---

cat <<EOF
<!-- generated by tests/common/compare.sh ${TOPO} ${SCENARIO} -->
<!-- sources:
EOF
for v in "${VARIANTS[@]}"; do
  echo "  ${v}: ${SUMMARY[$v]:-(missing)}"
done
echo "-->"
echo

echo "## TPC-C Results"
echo
echo "### tpmC"
echo
echo "| threads | vm | k8s-unlimit | k8s-limit |"
echo "|---------|----|----|----|"
for t in "${THREAD_LEVELS[@]}"; do
  printf "| %-3s | %s | %s | %s |\n" "$t" \
    "$(_int_comma "$(_field "${SUMMARY[vm]}" "$t" 2)")" \
    "$(_int_comma "$(_field "${SUMMARY[k8s-unlimit]}" "$t" 2)")" \
    "$(_int_comma "$(_field "${SUMMARY[k8s-limit]}" "$t" 2)")"
done
echo

echo "### NEW_ORDER p99 (ms)"
echo
echo "| threads | vm | k8s-unlimit | k8s-limit |"
echo "|---------|----|----|----|"
for t in "${THREAD_LEVELS[@]}"; do
  printf "| %-3s | %s | %s | %s |\n" "$t" \
    "$(_num "$(_field "${SUMMARY[vm]}" "$t" 3)")" \
    "$(_num "$(_field "${SUMMARY[k8s-unlimit]}" "$t" 3)")" \
    "$(_num "$(_field "${SUMMARY[k8s-limit]}" "$t" 3)")"
done
echo

echo "### PAYMENT p99 (ms)"
echo
echo "| threads | vm | k8s-unlimit | k8s-limit |"
echo "|---------|----|----|----|"
for t in "${THREAD_LEVELS[@]}"; do
  printf "| %-3s | %s | %s | %s |\n" "$t" \
    "$(_num "$(_field "${SUMMARY[vm]}" "$t" 4)")" \
    "$(_num "$(_field "${SUMMARY[k8s-unlimit]}" "$t" 4)")" \
    "$(_num "$(_field "${SUMMARY[k8s-limit]}" "$t" 4)")"
done
echo

# --- peak / scaling ---

vm_peak=$(_peak vm); ku_peak=$(_peak k8s-unlimit); kl_peak=$(_peak k8s-limit)
vm_pv=${vm_peak%|*}; vm_pt=${vm_peak#*|}
ku_pv=${ku_peak%|*}; ku_pt=${ku_peak#*|}
kl_pv=${kl_peak%|*}; kl_pt=${kl_peak#*|}

echo "### Peak tpmC"
echo
echo "| variant | peak tpmC | 達峰 thread | vs VM peak |"
echo "|---------|-----------|-------------|------------|"
printf "| vm           | %s | %st | baseline |\n"   "$(_int_comma "$vm_pv")" "$vm_pt"
printf "| k8s-unlimit  | %s | %st | %s |\n"         "$(_int_comma "$ku_pv")" "$ku_pt" "$(_pct "$ku_pv" "$vm_pv")"
printf "| k8s-limit    | %s | %st | %s |\n"         "$(_int_comma "$kl_pv")" "$kl_pt" "$(_pct "$kl_pv" "$vm_pv")"
echo

echo "### Scaling"
echo
echo "| variant | 16t | 32t | 64t | 128t | scaling (16t→peak) |"
echo "|---------|-----|-----|-----|------|--------------------|"
for v in "${VARIANTS[@]}"; do
  s16=$(_field "${SUMMARY[$v]}" 16 2)
  s32=$(_field "${SUMMARY[$v]}" 32 2)
  s64=$(_field "${SUMMARY[$v]}" 64 2)
  s128=$(_field "${SUMMARY[$v]}" 128 2)
  peak_pair=$(_peak "$v"); peak=${peak_pair%|*}
  printf "| %-12s | %s | %s | %s | %s | %s |\n" "$v" \
    "$(_int_comma "$s16")" "$(_int_comma "$s32")" \
    "$(_int_comma "$s64")" "$(_int_comma "$s128")" \
    "$(_pct "$peak" "$s16")"
done
echo

# --- loss analysis ---

echo "### 量測一：VM → K8s-unlimit"
echo
echo "| threads | vm | k8s-unlimit | tpmC 損耗 | NO p99 Δ (ms) | PAY p99 Δ (ms) |"
echo "|---------|----|----|-----------|---------------|----------------|"
for t in "${THREAD_LEVELS[@]}"; do
  vm_t=$(_field "${SUMMARY[vm]}" "$t" 2);  ku_t=$(_field "${SUMMARY[k8s-unlimit]}" "$t" 2)
  vm_n=$(_field "${SUMMARY[vm]}" "$t" 3);  ku_n=$(_field "${SUMMARY[k8s-unlimit]}" "$t" 3)
  vm_p=$(_field "${SUMMARY[vm]}" "$t" 4);  ku_p=$(_field "${SUMMARY[k8s-unlimit]}" "$t" 4)
  printf "| %-3s | %s | %s | %s | %s | %s |\n" "$t" \
    "$(_int_comma "$vm_t")" "$(_int_comma "$ku_t")" \
    "$(_pct "$ku_t" "$vm_t")" "$(_delta "$ku_n" "$vm_n")" "$(_delta "$ku_p" "$vm_p")"
done
echo

echo "### 量測二：K8s-unlimit → K8s-limit"
echo
echo "| threads | k8s-unlimit | k8s-limit | tpmC 損耗 | NO p99 Δ (ms) | PAY p99 Δ (ms) |"
echo "|---------|----|----|-----------|---------------|----------------|"
for t in "${THREAD_LEVELS[@]}"; do
  ku_t=$(_field "${SUMMARY[k8s-unlimit]}" "$t" 2); kl_t=$(_field "${SUMMARY[k8s-limit]}" "$t" 2)
  ku_n=$(_field "${SUMMARY[k8s-unlimit]}" "$t" 3); kl_n=$(_field "${SUMMARY[k8s-limit]}" "$t" 3)
  ku_p=$(_field "${SUMMARY[k8s-unlimit]}" "$t" 4); kl_p=$(_field "${SUMMARY[k8s-limit]}" "$t" 4)
  printf "| %-3s | %s | %s | %s | %s | %s |\n" "$t" \
    "$(_int_comma "$ku_t")" "$(_int_comma "$kl_t")" \
    "$(_pct "$kl_t" "$ku_t")" "$(_delta "$kl_n" "$ku_n")" "$(_delta "$kl_p" "$ku_p")"
done
echo

echo "### 量測三：VM → K8s-limit（生產部署總損耗）"
echo
echo "| threads | vm | k8s-limit | tpmC 損耗 | NO p99 Δ (ms) | PAY p99 Δ (ms) |"
echo "|---------|----|----|-----------|---------------|----------------|"
for t in "${THREAD_LEVELS[@]}"; do
  vm_t=$(_field "${SUMMARY[vm]}" "$t" 2);  kl_t=$(_field "${SUMMARY[k8s-limit]}" "$t" 2)
  vm_n=$(_field "${SUMMARY[vm]}" "$t" 3);  kl_n=$(_field "${SUMMARY[k8s-limit]}" "$t" 3)
  vm_p=$(_field "${SUMMARY[vm]}" "$t" 4);  kl_p=$(_field "${SUMMARY[k8s-limit]}" "$t" 4)
  printf "| %-3s | %s | %s | %s | %s | %s |\n" "$t" \
    "$(_int_comma "$vm_t")" "$(_int_comma "$kl_t")" \
    "$(_pct "$kl_t" "$vm_t")" "$(_delta "$kl_n" "$vm_n")" "$(_delta "$kl_p" "$vm_p")"
done
