{
 "title": "Redis 監控重構",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Key alerting rules included", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Redis Up/Down (Alert Status = 0)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_up{instance =~ \".*\"}",
     "legendFormat": "{{instance}}",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "RedisTooManyConnections (Max: 10000 ; Alert 70%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_connected_clients{instance=~\".*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RedisOutOfMemory (Alert 80%))",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * (redis_memory_used_bytes{instance=~\".*\"}  / redis_config_maxmemory{instance=~\".*\"} )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Key metrics included", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Commands Executed / sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{instance=~\".*\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, irate(redis_command_call_duration_seconds_count{instance=~\".*\"} [2m]))",
     "legendFormat": "{{instance}} {{ cmd }}"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{instance=~\".*\"}[5m])",
     "legendFormat": "{{instance}} hits"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{instance=~\".*\"}[5m])",
     "legendFormat": "{{instance}} misses"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{instance=~\"rdb.*\"}",
     "legendFormat": "{{instance}} used"
    },
    {
     "expr": "redis_config_maxmemory{instance=~\"rdb.*\"}",
     "legendFormat": "{{instance}} max"
    },
    {
     "expr": "redis_memory_used_rss_bytes{instance=~\"rdb.*\"}",
     "legendFormat": "{{instance}} used rss"
    },
    {
     "expr": "redis_memory_fragmentation_ratio{instance=~\"rdb.*\"}",
     "legendFormat": "{{instance}} fragmentation_ratio"
    }
   ]
  },
  {
   "title": "Redis Clients",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_connected_clients{instance=~\".*\"}",
     "legendFormat": "{{ instance }} connected clients"
    },
    {
     "expr": "redis_blocked_clients{instance=~\".*\"}",
     "legendFormat": "{{ instance }} blocked_clients"
    }
   ]
  },
  {
   "title": "Redis_Master_last_io_seconds",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ops", "label": "IOPS" }
   ],
   "targets": [
    {
     "expr": "redis_master_last_io_seconds_ago{instance=~\"rdb.*\"}",
     "legendFormat": "{{instance}} delay ops"
    }
   ]
  },
  {
   "title": "Redis_Connected_Slaves",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_connected_slaves{instance=~\"rdb.*\"}",
     "legendFormat": "{{instance}} connected slaves"
    }
   ]
  },
  {
   "title": "Expired / Evicted / All Keys / Keys expiring (Last 5 min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{instance=~\".*\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{instance=~\".*\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} evicted"
    },
    {
     "expr": "sum(rate(redis_db_keys{instance=~\".*\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} keys"
    },
    {
     "expr": "sum(rate(redis_db_keys_expiring{instance=~\".*\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} keys expiring"
    }
   ]
  }
 ]
}