apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dbaas
  namespace: argocd
spec:
  description: DBaaS lab GitOps project
  sourceRepos:
    - '*'
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: dbaas-system
      server: https://kubernetes.default.svc
    - namespace: private-demo
      server: https://kubernetes.default.svc
    - namespace: percona-operator
      server: https://kubernetes.default.svc
    - namespace: mysql-single
      server: https://kubernetes.default.svc
    - namespace: mysql-single-1
      server: https://kubernetes.default.svc
    - namespace: mysql-single-2
      server: https://kubernetes.default.svc
    - namespace: mysql-single-3
      server: https://kubernetes.default.svc
    - namespace: mysql-single-4
      server: https://kubernetes.default.svc
    - namespace: mysql-single-5
      server: https://kubernetes.default.svc
    - namespace: mysql-single-6
      server: https://kubernetes.default.svc
    - namespace: mysql-single-7
      server: https://kubernetes.default.svc
    - namespace: mysql-single-8
      server: https://kubernetes.default.svc
    - namespace: mysql-single-9
      server: https://kubernetes.default.svc
    - namespace: mysql-single-10
      server: https://kubernetes.default.svc
    - namespace: tidb-operator
      server: https://kubernetes.default.svc
    - namespace: tidb-cluster
      server: https://kubernetes.default.svc
    - namespace: redis-operator
      server: https://kubernetes.default.svc
    - namespace: redis-single
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
