apiVersion: v1
kind: Secret
metadata: {name: mysql-single-8-secrets, namespace: mysql-single-8}
type: Opaque
stringData: {root: root123456, xtrabackup: xtrabackup123456, monitor: monitor123456, proxyadmin: proxyadmin123456, operator: operator123456, replication: repl123456}
