version: '3'
services:
  redis-master:
    container_name: redis-master
    image: redis
    ports:
      - "6379:6379"
  redis-slave:
    container_name: redis-slave
    image: redis
    command: redis-server --slaveof redis-master 6379
    links:
      - redis-master
    ports:
      - "6380:6379"
  redis-sentinel-1:
    container_name: redis-sentinel-1
    build: sentinel
    links:
      - redis-master
  redis-sentinel-2:
    container_name: redis-sentinel-2
    build: sentinel
    links:
      - redis-master
  redis-sentinel-3:
    container_name: redis-sentinel-3
    build: sentinel
    links:
      - redis-master
