version: '3'
services:
  redis-master1:
    container_name: redis-master1
    image: redis
    ports:
      - "6379:6379"
  redis-slave1:
    container_name: redis-slave1
    image: redis
    command: redis-server --slaveof redis-master1 6379
    links:
      - redis-master1
    ports:
      - "6380:6379"
  redis-master2:
    container_name: redis-master2
    image: redis
    ports:
      - "6381:6379"
  redis-slave2:
    container_name: redis-slave2
    image: redis
    command: redis-server --slaveof redis-master2 6379
    links:
      - redis-master2
    ports:
      - "6382:6379"
  redis-sentinel-1:
    container_name: redis-sentinel-1
    build: sentinel
    links:
      - redis-master1
      - redis-master2
  redis-sentinel-2:
    container_name: redis-sentinel-2
    build: sentinel
    links:
      - redis-master1
      - redis-master2
  redis-sentinel-3:
    container_name: redis-sentinel-3
    build: sentinel
    links:
      - redis-master1
      - redis-master2
