apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: minimal-cluster
  namespace: mysql-single
spec:
  crVersion: 1.16.1
  secretsName: minimal-cluster-secrets
  unsafeFlags:
    tls: true
    pxcSize: true
    proxySize: true
  upgradeOptions:
    apply: disabled
    schedule: "0 4 * * *"
  tls:
    enabled: false
  pxc:
    size: 1
    image: percona/percona-xtradb-cluster:8.0.39-30.1
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1
        memory: 2Gi
    volumeSpec:
      persistentVolumeClaim:
        storageClassName: local-path
        resources:
          requests:
            storage: 6Gi
  haproxy:
    enabled: true
    size: 1
    image: percona/haproxy:2.8.11
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
  proxysql:
    enabled: false
  logcollector:
    enabled: false
  backup:
    image: percona/percona-xtradb-cluster-operator:1.16.1-pxc8.0-backup-pxb8.0.35
