apiVersion: v1
kind: Secret
metadata:
  name: mysqld-exporter
  namespace: mysql-single
type: Opaque
stringData:
  .my.cnf: |
    [client]
    user=monitor
    password=monitor123456
    host=minimal-cluster-haproxy
    port=3306
